### PR TITLE
Set port for enrollz and attestz gRPC endpoints

### PR DESCRIPTION
**Pull request by jenia-grunin**

### CODE REVIEW

**Review by LimeHat — APPROVED** [review]
lgtm. note we also need a grpc service identity (identities?) in OpenConfig yang, like https://github.com/openconfig/public/blob/ea279957a8dab6eb0c0b05e5a134bc3dfb0c8d28/release/models/gnsi/openconfig-gnsi.yang#L35-L40

**Comment by jenia-grunin** [comment]
> lgtm. note we also need a grpc service identity (identities?) in OpenConfig yang, like https://github.com/openconfig/public/blob/ea279957a8dab6eb0c0b05e5a134bc3dfb0c8d28/release/models/gnsi/openconfig-gnsi.yang#L35-L40

Thanks, Sergey! Could you remind me why the YANG model is needed and how it is used? 

I would also hope there are proto-to-yang converters and yang-validators out there, so I don't need to do it by hand?

**Comment by LimeHat** [comment]
And just to clarify, my comments are not directly related to this PR; yang update should probably be done as a separate PR in `openconfig/public` repo. But since this change talks about grpc-server configurations where gNMI/... reside on the same socket with enrollz/attestz I thought it is a good time to raise this topic :)

**Comment by jenia-grunin** [comment]
Hey, @openconfig/attestz-triage , instead of creating per-vendor bugs and asking to review/sign-off on each PR, we now have  `attestz-triage` group which we will be adding to the PRs that introduce important changes (APIs, design, workflow, etc). This should streamline iteration on such changes, and make life easier for everyone :) So for this PR, for example, the expectation is at least one person from each vendor will review and explicitly approve it. Please let me know if this helps and suggest any improvement to the process.

I am also going to suggest creating per-vendor groups for the entire OC org. That way (1) we can add each vendor separately to PRs and clearly see who reviewed/approved it and (2) we don't have to repeat the same process for each repo in openconfig. Please let me know what you think, and happy to discuss next week during the weekly Tue morning OC meeting.

**Comment by jenia-grunin** [comment]
> s is going to be a simple "one-liner"

ah gotcha, thanks! Ok, I will add it this then in a separate PR. I asked about proto-to-yang converter, because I also saw more service-specific yang files, such as [this one for certz](https://github.com/openconfig/public/blob/ea279957a8dab6eb0c0b05e5a134bc3dfb0c8d28/release/models/gnsi/openconfig-gnsi-certz.yang). Would we need something like that for enrollz and attestz as well?

**Review by rnhaddad — APPROVED** [review]
Looks good to me

**Review by morrowc — APPROVED** [review]

**Comment by LimeHat** [comment]
Hi @jenia-grunin,
 > Would we need something like that for enrollz and attestz as well?

No, probably not. Unless you need additional state that can be retrieved via gNMI telemetry. But that's not in the current scope of attestz/enrollz AFAIK.

**Pull request merged**
